# Site settings
title: ranwu.me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ranwu.me" # the base hostname & protocol for your site
github_username:  xing-zhi

# Build settings
markdown: kramdown
